### ISSUE TITLE
插件加载错误：There is no current event loop in thread 'MainThread'

### ISSUE THREAD

**Issue by Hazerplus** [canxin121/nonebot_plugin_bind#3]
作为 `nonebot_plugin_spark_gpt` 的依赖安装，但是 `nonebot_plugin_bind` 加载错误

bot本体使用小派蒙 `LittlePaimon`
[https://github.com/CMHopeSunshine/LittlePaimon](url)

系统版本     `Ubuntu 22.04.2 LTS`

python版本 `3.10.12`

具体报错如下：

> 10-17 19:28:49 [ERROR] nonebot | Failed to import "nonebot_plugin_bind"
Traceback (most recent call last):
  File "/home/bot/LittlePaimon/LittlePaimon/bot.py", line 27, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "/home/bot/LittlePaimon/LittlePaimon/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 130, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/home/bot/LittlePaimon/LittlePaimon/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 64, in load_all_plugins
    return manager.load_all_plugins()
  File "/home/bot/LittlePaimon/LittlePaimon/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 176, in load_all_plugins
    return set(
  File "/home/bot/LittlePaimon/LittlePaimon/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 177, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
  File "/home/bot/LittlePaimon/LittlePaimon/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/bot/LittlePaimon/LittlePaimon/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bot/LittlePaimon/LittlePaimon/.venv/lib/python3.10/site-packages/nonebot_plugin_spark_gpt/__init__.py", line 8, in <module>
    require("nonebot_plugin_bind")
  File "/home/bot/LittlePaimon/LittlePaimon/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 179, in require
    plugin = load_plugin(name)
  File "/home/bot/LittlePaimon/LittlePaimon/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 39, in load_plugin
    return manager.load_plugin(module_path)
> File "/home/bot/LittlePaimon/LittlePaimon/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/bot/LittlePaimon/LittlePaimon/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bot/LittlePaimon/LittlePaimon/.venv/lib/python3.10/site-packages/nonebot_plugin_bind/__init__.py", line 57, in <module>
    bind_info = on_alconna(Alconna(Command_Start, "bindinfo", Option("-group")))
  File "/home/bot/LittlePaimon/LittlePaimon/.venv/lib/python3.10/site-packages/nonebot_plugin_alconna/matcher.py", line 533, in on_alconna
    _rule = alconna(
  File "/home/bot/LittlePaimon/LittlePaimon/.venv/lib/python3.10/site-packages/tarina/tools.py", line 76, in inner
    return func(fn(*args, **kwargs))  # type: ignore
  File "/home/bot/LittlePaimon/LittlePaimon/.venv/lib/python3.10/site-packages/nonebot_plugin_alconna/rule.py", line 90, in __init__
    self._future: asyncio.Future = asyncio.Future()
  File "/usr/lib/python3.10/asyncio/events.py", line 656, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainThread'.
![image](https://github.com/canxin121/nonebot_plugin_bind/assets/128805772/54edd6f8-86f0-43d6-b614-579cc7660f07)

> 10-17 19:28:49 [ERROR] nonebot | Failed to import "nonebot_plugin_spark_gpt"
Traceback (most recent call last):
  File "/home/bot/LittlePaimon/LittlePaimon/bot.py", line 27, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "/home/bot/LittlePaimon/LittlePaimon/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 130, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/home/bot/LittlePaimon/LittlePaimon/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 64, in load_all_plugins
    return manager.load_all_plugins()
  File "/home/bot/LittlePaimon/LittlePaimon/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 176, in load_all_plugins
    return set(
  File "/home/bot/LittlePaimon/LittlePaimon/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 177, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/home/bot/LittlePaimon/LittlePaimon/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/bot/LittlePaimon/LittlePaimon/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bot/LittlePaimon/LittlePaimon/.venv/lib/python3.10/site-packages/nonebot_plugin_spark_gpt/__init__.py", line 8, in <module>
    require("nonebot_plugin_bind")
  File "/home/bot/LittlePaimon/LittlePaimon/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 183, in require
    raise RuntimeError(f'Cannot load plugin "{name}"!')
RuntimeError: Cannot load plugin "nonebot_plugin_bind"!
![image](https://github.com/canxin121/nonebot_plugin_bind/assets/128805772/45dc08f1-7ebe-4992-83a6-cd4216c6367f)

**Comment by luluxiaoyu** [comment]
同样有该问题

**Comment by adios-amigos** [comment]
同样发生该错误
